services:
  timesheet-api:
    build:
      context: .
      dockerfile: timesheet-api/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DEFAULT_PORT:-3000}:${TIMESHEET_PORT}"
    